server:
  port: 8080

spring:
  datasource:
    hikari:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/it1660
    username: it1660
    password: it1660
  #    driver-class-name: org.h2.Driver     # [ h2 설정 ]

  # [ h2 설정 ]
  #  h2:
  #    console:
  #      enabled: true

  devtools:
    livereload:
      enabled: true

  sql:
    init:
      mode: always
    #      schema-locations: schema.sql
    #      data-locations: data.sql

    # Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false
  #    check-template-location: true
  #    prefix: classpath:/templates/thymeleafEx
  #    suffix: .html

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    hibernate:
      default_batch_fetch_size: '1000'
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true


mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.gsitm.career

#logging.level:
#  jdbc:
#    sqlonly: debug
#    sqltiming: info
#    resultsettable: info
#    audit: off
#    resultset: off
#    connection: off
#  org.hibernate.SQL: trace







itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/
