server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/internStudy
    username: root
    password: it1437
  #Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  #    driver-class-name: org.h2.Driver     # [ h2 설정 ]

# [ h2 설정 ]
#  h2:
#    console:
#      enabled: true

  #live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  sql:
    init:
      mode: always
  #      schema-locations: schema.sql
  #      data-locations: data.sql

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # 쿼리 성능 향상
        default_batch_fetch_size: 1000
      format_sql: true
    show-sql: true
    generate-ddl: true

mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.gsitm.career

# 상품 이미지 업로드 경로
itemImgLocation: C:/shop/item

# 리소스 업로드 경로
uploadPath: file:///C:/shop/
