server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/it1663
    username: it1663
    password: it1663
  #    driver-class-name: org.h2.Driver     # [ h2 설정 ]

  # [ h2 설정 ]
  #  h2:
  #    console:
  #      enabled: true

  #LiveReload 활성화
  devtools:
    livereload:
      enabled: true

  #Thymeleaf cache 사용중지 (운영환경에서는 캐싱 기능사용, 개발환경에서는 캐싱 기능을 꺼둠)
  thymeleaf:
    cache: false

  sql:
    init:
      mode: always
  #      schema-locations: schema.sql
  #      data-locations: data.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true


mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.gsitm.career
