server:
  port: 8080
  #오류 응답에 exception의 내용을 포함할지 여부
#  error:
#    include-exception: true
#    #오류 응답에 stacktrace 내용을 포함할지 여부 (ALWAYS, NEVER, ON_TRACE_PARAM)
#    include-stacktrace: always
#    #브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부
#    whitelabel:
#      enabled: false


spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/it1668 # 사번 기입
      username: it1668 # 사번 기입
      password: it1668 # 사번 기입
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/intern
  #    username: admin
  #    password: itm6700!
  profiles:
    include: oauth

  devtools:
    livereload:
      enabled: true

  sql:
    init:
      mode: always
    #      schema-locations: schema.sql
    #      data-locations: data.sql

    # Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false
  #    check-template-location: true
  #    prefix: classpath:/templates/thymeleafEx
  #    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update #create
      database-platform: org.hibernate.dialect.MySQL8Dialect // hibernate sql 문
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size : 1000
mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.gsitm.career

logging.level:
  jdbc:
    sqlonly: debug
    sqltiming: info
    resultsettable: info
    audit: off
    resultset: off
    connection: off
  org.hibernate.SQL: trace

itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/