server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/it1666
      username: it1661
      password: it1661
  jpa:
    properties:
      hibernate:
        show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: =classpath:/webapp/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.shop

